apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: providers.provider.example.com
spec:
  group: provider.example.com
  names:
    kind: Provider
    listKind: ProviderList
    plural: providers
    singular: provider
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Provider is a specification for a Provider resource
        properties:
          spec:
            description: ProviderSpec is the spec for a Provider resource
            properties:
              dataSourceName:
                type: string
            # Add provider specific data source properties
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
